databases:
  - name: myapp_db
    databaseName: myapp_db
    user: myapp
    region: singapore

services:
  - type: web
    name: myapp
    env: ruby
    rootDir: backend # ここにルートディレクトリを指定
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
